let resettingLocalData = false;

'use strict';
const ASSETS = {
  "thestral": "assets/thestral.png",
  "hippogriff": "assets/hippogriff.png",
  "boggart": "assets/boggart.png",
  "grindylow": "assets/grindylow.png",
  "acromantula": "assets/acromantula.png",
  "dementor": "assets/dementor.png",
  "gryffindor": "assets/gryffindor.svg",
  "hufflepuff": "assets/hufflepuff.svg",
  "ravenclaw": "assets/ravenclaw.svg",
  "slytherin": "assets/slytherin.svg"
};

const pair=(en,zh)=>({en,zh});
let lang='en';
const t=x=>typeof x==='string'?x:x[lang];
const houses=[
{id:'gryffindor',name:pair('Gryffindor','格兰芬多'),color:'#ce7872',symbol:'♌',traits:pair('Courage · bravery · determination','勇气 · 胆识 · 决心'),story:pair('Step forward even when the forest looks dark. Your story celebrates courage and protecting others.','即使前路幽暗，也勇敢向前。你的故事强调勇气与保护他人。'),cue:pair('Take a breath. Courage is trying again.','深呼吸，愿意再试一次就是勇气。')},
{id:'hufflepuff',name:pair('Hufflepuff','赫奇帕奇'),color:'#ddba62',symbol:'✿',traits:pair('Patience · loyalty · fairness','耐心 · 忠诚 · 公平'),story:pair('Care for creatures and stay with your friends. Your story celebrates steady practice and kindness.','照顾神奇动物，陪伴同伴。你的故事强调耐心练习与善意。'),cue:pair('One careful answer at a time.','一道一道，耐心就会带来进步。')},
{id:'ravenclaw',name:pair('Ravenclaw','拉文克劳'),color:'#82b3db',symbol:'✧',traits:pair('Wisdom · curiosity · creativity','智慧 · 好奇 · 创造力'),story:pair('Notice patterns and ask why. Your story celebrates observation and clever solutions.','发现规律，追问原因。你的故事强调观察与巧妙解法。'),cue:pair('Look at the sign, then find a pattern.','先看运算符，再找计算规律。')},
{id:'slytherin',name:pair('Slytherin','斯莱特林'),color:'#83c29d',symbol:'◇',traits:pair('Ambition · resourcefulness · determination','抱负 · 机敏 · 决心'),story:pair('Plan your route and use what you know. Your story celebrates strategy and purposeful practice.','规划路线，善用所学。你的故事强调策略与有目标的练习。'),cue:pair('Think ahead. You have a plan.','提前思考，你已经有了计划。')}
];
const spells={
lumos:{name:pair('Wand-Lighting Charm','照明咒'),words:'Lumos',effect:pair('Light your wand and illuminate the path.','点亮魔杖，照亮林间小径。'),gesture:pair('Raise the wand gently.','轻轻抬起魔杖。')},
accio:{name:pair('Summoning Charm','飞来咒'),words:'Accio',effect:pair('Summon the feeding basket, not the creature.','召来食物篮，而不是召唤动物本身。'),gesture:pair('Point towards the basket and draw it closer.','指向食物篮，轻轻向自己引回。')},
riddikulus:{name:pair('Boggart-Banishing Spell','滑稽滑稽'),words:'Riddikulus',effect:pair('Imagine a funny form to make your fear ridiculous.','想象滑稽的样子，让恐惧变得可笑。'),gesture:pair('Point your wand and picture something funny.','举起魔杖，想象一件好笑的事。')},
relashio:{name:pair('Revulsion Jinx','力松劲泄'),words:'Relashio',effect:pair('Force a gripping creature to release its hold.','让紧抓不放的生物松开。'),gesture:pair('Aim at the grip and flick the wand away.','对准抓握的位置，向外挥动魔杖。')},
impedimenta:{name:pair('Impediment Jinx','障碍重重'),words:'Impedimenta',effect:pair('Slow the threat while you retreat to safety.','阻碍威胁的行动，为安全撤离争取时间。'),gesture:pair('Trace a short line across your path.','在面前划出短短的一道。')},
patronus:{name:pair('Patronus Charm','守护神咒'),words:'Expecto Patronum',effect:pair('Focus on a happy memory and cast a silver protector to repel Dementors.','专注于幸福的记忆，召唤银色守护神驱散摄魂怪。'),gesture:pair('Lift your wand and hold your happy memory.','举起魔杖，牢牢记住幸福的时刻。')}
};
const levels=[
{id:'thestral',name:pair('Thestral','夜骐'),place:pair('Forbidden Forest · The forest edge','禁林 · 林缘'),desc:pair('A winged horse with a skeletal body. Only people who have witnessed and understood death can see one. Thestrals are not evil.','一种骨骼轮廓鲜明的有翼马。只有见证并理解死亡的人才能看见它们；夜骐并不邪恶。'),action:pair('It unfolds its wings and lowers its head.','它展开翅膀，轻轻低下头。'),mission:pair('With Hagrid nearby, light the path and observe quietly. The field-guide illustration is visible to every player.','在海格陪同下照亮小径，安静观察。图鉴插画向所有玩家可见，不强加悲伤身世。'),spell:'lumos',goal:pair('Path illuminated','小径照明'),done:pair('The Thestral trusts your calm presence. The path is lit.','夜骐接纳了你安静的陪伴，小径亮起来了。')},
{id:'hippogriff',name:pair('Hippogriff','鹰头马身有翼兽'),place:pair('Forbidden Forest · Hagrid’s clearing','禁林 · 海格的空地'),desc:pair('An eagle-headed creature with a horse’s body and powerful wings. Proud and sensitive to manners, it should be approached respectfully.','拥有鹰的头部、马的身体和强壮翅膀。它们骄傲而重视礼节，接近时要保持尊重。'),action:pair('It watches your bow, then bows back.','它注视你的鞠躬，然后回礼。'),mission:pair('Bow and wait for its reply. Use Accio to bring Hagrid’s feeding basket closer.','先鞠躬，等待回礼，再用飞来咒取来海格的食物篮。'),spell:'accio',goal:pair('Care task','照护进度'),done:pair('The basket arrives and the Hippogriff accepts your care.','食物篮顺利送达，它接受了你的照顾。')},
{id:'boggart',name:pair('Boggart','博格特'),place:pair('Hogwarts · Defence Against the Dark Arts','霍格沃茨 · 黑魔法防御术教室'),desc:pair('A shape-shifter that takes the form of what you fear most. Laughter and Riddikulus help defeat it.','会变成你最害怕事物的变形生物。笑声与滑稽滑稽咒能帮助你击退它。'),action:pair('It slips out of a cupboard, trying on a frightening shape.','它从柜子里钻出来，尝试变成吓人的模样。'),mission:pair('Imagine its boots turning into enormous fluffy slippers. Keep the scene light and funny.','想象它的靴子变成巨大的毛绒拖鞋，让场面轻松好笑。'),spell:'riddikulus',goal:pair('Fear dispelled','恐惧驱散'),done:pair('A burst of laughter sends the Boggart back into hiding.','一阵笑声让博格特躲了回去。')},
{id:'grindylow',name:pair('Grindylow','格林迪洛'),place:pair('Black Lake · The shallows','黑湖 · 浅水区'),desc:pair('A small horned water demon with long fingers. It grabs at swimmers; its strong grip is the danger to watch.','一种长角的小型水魔，有细长手指，会抓住游泳者；需要留意它的抓握。'),action:pair('It rises through the weeds and grips a training rope.','它从水草间探出头，抓住训练绳。'),mission:pair('Practise from a supervised lakeside platform. Use Relashio to free the rope.','在有人指导的湖边平台上练习，用力松劲泄让训练绳脱离抓握。'),spell:'relashio',goal:pair('Rope released','脱困进度'),done:pair('The rope is free. You return to the lakeside platform.','训练绳松开了，你安全回到湖边平台。')},
{id:'acromantula',name:pair('Acromantula','八眼巨蛛'),place:pair('Forbidden Forest · The webbed trail','禁林 · 蛛网小径'),desc:pair('A huge, eight-eyed spider capable of speech. A colony lives in the Forbidden Forest; keep your distance.','能够说话、长有八只眼睛的巨型蜘蛛。禁林里生活着它们的族群，遇见时要保持距离。'),action:pair('It steps across the trail and clicks its pincers.','它横跨小径，发出螯肢咔哒声。'),mission:pair('Slow its approach with Impedimenta and clear a retreat route.','用障碍重重延缓它的接近，留出撤离路线。'),spell:'impedimenta',goal:pair('Retreat secured','撤离进度'),done:pair('You lead the group away from the webbed trail.','你带领同伴撤出了蛛网小径。')},
{id:'dementor',name:pair('Dementor','摄魂怪'),place:pair('Hogwarts · Patronus training','霍格沃茨 · 守护神训练场'),desc:pair('A hooded dark being that drains happiness and brings a terrible chill. A Patronus can drive it away.','一种披着斗篷、吸走快乐并带来寒意的黑暗生物。守护神可以将它驱散。'),action:pair('It glides closer as a cold mist gathers.','它缓缓飘近，周围凝起冷雾。'),mission:pair('Remember a happy moment and summon your Patronus. Your professor is here to guide you.','回想一个幸福的时刻，召唤你的守护神。教授会在身旁指引你。'),spell:'patronus',goal:pair('Patronus strength','守护神力量'),done:pair('Silver light clears the mist. Your first Hogwarts chapter is complete.','银光驱散冷雾，你完成了霍格沃茨的第一章。')}
];
const cfg={range:20,operations:'mixed',count:50,visible:5,mode:'timed-correction'};
let house='gryffindor',levelIndex=0,phase='world',run=null,cleared=new Set(),demoAction=false,feedback=null;
const $=id=>document.getElementById(id);
const H=()=>houses.find(h=>h.id===house);
const L=()=>levels[levelIndex];
const spellKey=()=>L().spell;
const S=()=>spells[spellKey()];
function art(id){return `<img class="creature-art" src="${ASSETS[id]}" alt="${t(levels.find(l=>l.id===id).name)} · ${t(pair('AI game-style illustration','AI 游戏风格插画'))}" width="1536" height="1024">`}
function select(id,label,options,value){return `<label>${label}<select id="${id}">${options.map(([v,name])=>`<option value="${v}" ${String(v)===String(value)?'selected':''}>${name}</option>`).join('')}</select></label>`}
const WEEKLY_KEY='m-math-hogwarts-weekly-v1';
let storageError=false,weekly=null;
function dateKey(date=new Date(),zone=weekly?.timeZone||Intl.DateTimeFormat().resolvedOptions().timeZone){const p=new Intl.DateTimeFormat('en-US',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);const val=k=>p.find(x=>x.type===k).value;return `${val('year')}-${val('month')}-${val('day')}`}
function addDays(key,n){const d=new Date(key+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
function weekKey(key=dateKey()){const day=new Date(key+'T12:00:00Z').getUTCDay();return addDays(key,-((day+6)%7))}
function freshWeekly(){const timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone;const today=dateKey(new Date(),timeZone);return {version:1,timeZone,week:weekKey(today),level:0,pieces:0,days:{},completed:[],awarded:[],lastDate:today,notice:null}}
function validWeekly(w){if(!w||w.version!==1||!Number.isInteger(w.level)||w.level<0||w.level>=6||!Number.isInteger(w.pieces)||w.pieces<0||w.pieces>12||!/^\d{4}-\d{2}-\d{2}$/.test(w.week)||!/^\d{4}-\d{2}-\d{2}$/.test(w.lastDate)||!Array.isArray(w.completed)||w.completed.length>6||!Array.isArray(w.awarded)||w.awarded.length>12||!w.days||typeof w.days!=='object')return false;try{new Intl.DateTimeFormat('en-US',{timeZone:w.timeZone}).format()}catch{return false}return Object.entries(w.days).every(([d,n])=>/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isInteger(n)&&n>=0&&n<=3)&&Object.values(w.days).reduce((a,b)=>a+b,0)===w.pieces&&w.completed.every((c,i)=>c.id===levels[i].id&&/^\d{4}-\d{2}-\d{2}$/.test(c.week))}
function readWeekly(){try{const raw=localStorage.getItem(WEEKLY_KEY);if(raw){const w=JSON.parse(raw);if(!validWeekly(w))throw Error('invalid save');return w}}catch{storageError=true}return null}
function saveWeekly(){if(resettingLocalData)return false;try{localStorage.setItem(WEEKLY_KEY,JSON.stringify(weekly));storageError=false;return true}catch{storageError=true;return false}}
function syncWeekly(){const saved=readWeekly();if(saved)weekly=saved;else if(!weekly)weekly=freshWeekly();const today=dateKey();const wk=weekKey(today);if(today<weekly.lastDate){cleared=new Set(weekly.completed.map(c=>c.id));return}
 if(wk>weekly.week){const done=weekly.pieces===12;if(weekly.completed.length===6){weekly.notice='all-done';}else{weekly.notice=done?'advanced':'reset';if(done)weekly.level++;weekly.week=wk;weekly.pieces=0;weekly.days={};weekly.awarded=[];}weekly.lastDate=today;saveWeekly()}
 else if(today>weekly.lastDate){weekly.lastDate=today;saveWeekly()}
 cleared=new Set(weekly.completed.map(c=>c.id));
}
function rewardReason(){if(storageError)return 'storage';if(dateKey()<weekly.lastDate)return 'clock';if(weekly.completed.length===6)return 'chapter';if(levelIndex!==weekly.level)return 'replay';if(weekly.pieces>=12)return 'week';if((weekly.days[dateKey()]||0)>=3)return 'day';return null}
function reasonText(reason){return t(({storage:pair('Progress could not be saved. No piece was awarded. Check browser storage.','无法保存进度，本轮未发放碎片，请检查浏览器存储。'),clock:pair('The device date moved backwards. Rewards pause until the saved date.','设备日期早于存档日期，奖励暂停，等待恢复到已记录日期。'),chapter:pair('Chapter 01 is complete. More adventures will open in the future; enjoy free practice.','第一章已完成，更多冒险将在未来开启；现在可以自由练习。'),replay:pair('This is a completed level. Replays do not award new pieces.','这是已完成关卡，复习不会获得新碎片。'),week:pair('All 12 pieces are collected. The next level opens on '+addDays(weekly.week,7)+'.','12 片已集齐，下一关于 '+addDays(weekly.week,7)+' 开放。'),day:pair('Today’s 3 pieces are collected. Return tomorrow; extra practice earns no pieces.','今天的 3 片已集齐，明天再来；额外练习不再获得碎片。'),expired:pair('A new week started during this round. This old round earns no piece; start a fresh round.','本轮期间已跨周，旧题组不计入新周；请开始新一轮。'),failed:pair('The round did not finish in time; no piece was awarded.','未在时间内完成本轮，没有获得碎片。'),duplicate:pair('This round has already been rewarded.','本轮奖励已经领取，不会重复发放。')})[reason]||pair('One piece earned.','获得 1 个碎片。'))}
async function awardRound(){const apply=()=>{syncWeekly();if(run.rewardHandled)return;run.rewardHandled=true;if(!score().pass){run.reward={reason:'failed'};return}if(run.week!==weekly.week||run.levelId!==levels[weekly.level].id){run.reward={reason:run.week!==weekly.week?'expired':'replay'};return}if(weekly.awarded.includes(run.id)){run.reward={earned:true,recovered:true,day:dateKey(),pieces:weekly.pieces};return}const reason=rewardReason();if(reason){run.reward={reason};return}const before=JSON.parse(JSON.stringify(weekly));weekly.pieces++;const day=dateKey();weekly.days[day]=(weekly.days[day]||0)+1;weekly.awarded.push(run.id);if(weekly.pieces===12&&!weekly.completed.some(c=>c.id===L().id))weekly.completed.push({id:L().id,week:weekly.week});weekly.lastDate=day;if(!saveWeekly()){weekly=before;run.reward={reason:'storage'};return}cleared=new Set(weekly.completed.map(c=>c.id));run.reward={earned:true,day,pieces:weekly.pieces};};if(navigator.locks)await navigator.locks.request(WEEKLY_KEY,apply);else apply()}
function weeklyPanel(){const i=weekly.level,today=dateKey(),count=weekly.days[today]||0,allDone=weekly.completed.length===6;const days=Array.from({length:7},(_,i)=>addDays(weekly.week,i));return `<div class="weekly-panel"><div><div class="step">${t(pair('ONE LEVEL · ONE WEEK','每周专注一关'))}</div><h3>${t(levels[i].name)} · ${weekly.pieces} / 12 ${t(pair('pieces','碎片'))}</h3><p class="notice">${weekly.week} — ${addDays(weekly.week,6)} · ${weekly.timeZone}<br>${t(pair('Monday 00:00 → next Monday 00:00','周一 00:00 至下周一 00:00'))}</p><div class="meter"><span style="width:${weekly.pieces/12*100}%"></span></div><p>${t(pair('Today','今日'))}: <strong>${count}/3</strong> · ${t(pair('Still needed this week','本周还需'))}: <strong>${Math.max(0,12-weekly.pieces)}</strong></p><div class="week-days">${days.map((day,i)=>`<div class="week-day ${day===today?'today':''}"><small>${t(pair(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i],['一','二','三','四','五','六','日'][i]))}</small><span>${'●'.repeat(weekly.days[day]||0)}${'○'.repeat(3-(weekly.days[day]||0))}</span></div>`).join('')}</div><p>${allDone?t(pair('Chapter 01 complete. More adventures will open in the future.','第一章完成，更多冒险将在未来开启。')):weekly.pieces===12?reasonText('week'):t(pair('Complete 50 questions in time for one piece. Up to 3 per day, 12 per weekly level.','限时完成 50 题获得一片，每天最多 3 片，每周 12 片拼完本关。'))}</p>${weekly.notice==='reset'?`<p class="notice">${t(pair('New week: the unfinished puzzle restarted at 0. Completed levels remain saved.','新的一周：未完成拼图已归零，已通关关卡仍然保留。'))}</p>`:''}${weekly.notice==='advanced'?`<p class="notice">${t(pair('A new week has opened your next map region.','新的一周已为你开放下一片地图。'))}</p>`:''}<p class="notice">${t(pair('12 pieces = 600 questions across at least 4 days. Puzzle resets never delete learning records.','12 片共需 600 题，至少分 4 天完成。拼图重置不会删除学习记录。'))}</p></div><div><div class="puzzle-grid" role="img" aria-label="${t(levels[i].name)} ${weekly.pieces}/12">${Array.from({length:12},(_,n)=>`<div class="puzzle-piece ${n<weekly.pieces?'collected':'missing'}" style="${n<weekly.pieces?`background-image:url('${ASSETS[levels[i].id]}');background-position:${(n%4)*100/3}% ${Math.floor(n/4)*50}%`:''}"><span>${n<weekly.pieces?'':n+1}</span></div>`).join('')}</div><p class="notice">${t(pair('The creature portrait is revealed one piece at a time.','逐片揭开这位神奇生物的完整画像。'))}</p></div></div>`}
function persistenceNote(){return `<p class="notice ${storageError?'save-error':''}" role="status">${storageError?t(pair('Local saving is unavailable. No new puzzle rewards can be saved. Allow browser storage and reload this same file.','本地保存不可用，无法保存新的拼图奖励。请允许浏览器存储，再重新打开同一文件。')):t(pair('Weekly progress saves automatically in this browser. Keep using this file in this browser; clearing browser data removes the save.','每周进度自动保存在当前浏览器。请持续使用此浏览器和此文件；清理浏览器数据会删除存档。'))}</p>`}
syncWeekly();if(!storageError)saveWeekly();

const regions=[{id:'hogwarts',name:pair('Hogwarts','霍格沃茨'),sub:pair('Chapter 01 · Six weekly journeys','第一章 · 六段每周旅程'),x:28,y:25,icon:'♜',open:true},{id:'hogsmeade',name:pair('Hogsmeade','霍格莫德'),sub:pair('More adventures coming soon','更多冒险，即将开启'),x:73,y:25,icon:'⌂'},{id:'diagon-alley',name:pair('Diagon Alley','对角巷'),sub:pair('More adventures coming soon','更多冒险，即将开启'),x:27,y:72,icon:'✧'},{id:'ministry',name:pair('Ministry of Magic','魔法部'),sub:pair('Your future Auror journey','未来的傲罗之路'),x:74,y:72,icon:'⚑'}];
const openLevel=i=>i>=0&&i<=weekly.level;
let mapSelection=null;
function terrainMap(school=false){
 const areas=school?[
 {id:0,d:'M55 56L212 38 342 72 318 202 249 255 77 213 39 134Z',x:187,y:145},
 {id:1,d:'M342 72L531 44 645 96 604 213 472 259 318 202Z',x:477,y:148},
 {id:2,d:'M645 96L802 44 945 91 964 217 827 269 604 213Z',x:791,y:162},
 {id:3,d:'M827 269L964 217 951 411 873 510 690 481 662 362Z',x:821,y:393},
 {id:4,d:'M472 259L604 213 827 269 662 362 690 481 502 514 390 422Z',x:546,y:381},
 {id:5,d:'M77 213L249 255 318 202 472 259 390 422 502 514 277 521 76 462 34 348Z',x:235,y:378}
 ]:[
 {id:'hogwarts',d:'M106 80L245 29 389 53 449 142 379 267 217 286 85 214 62 137Z',x:257,y:159},
 {id:'hogsmeade',d:'M449 142L556 80 704 44 891 93 942 203 864 275 689 252 550 283 379 267Z',x:683,y:163},
 {id:'diagon-alley',d:'M85 214L217 286 379 267 550 283 469 415 345 513 163 489 70 402 46 303Z',x:269,y:383},
 {id:'ministry',d:'M550 283L689 252 864 275 967 343 916 471 752 515 585 483 469 415Z',x:714,y:388}
 ];
 const forest=Array.from({length:45},(_,i)=>{let x=50+(i*137)%895,y=40+(i*67)%449;return `<use href="#pine-${school}" x="${x}" y="${y}" opacity="${.18+(i%3)*.09}"/>`}).join('');
 return `<div class="terrain-shell"><svg class="terrain-map" viewBox="0 0 1000 555" role="group" aria-label="${t(school?pair('Hogwarts regional map','霍格沃茨区域地图'):pair('Wizarding World map','魔法世界地图'))}"><defs><linearGradient id="land-${school}" x2=".8" y2="1"><stop stop-color="#b5b786"/><stop offset=".55" stop-color="#879c73"/><stop offset="1" stop-color="#577968"/></linearGradient><pattern id="water-${school}" width="28" height="18" patternUnits="userSpaceOnUse"><path d="M0 9q7-5 14 0t14 0" stroke="#8cb4ad" fill="none" opacity=".18"/></pattern><g id="pine-${school}" stroke="#284d38" fill="#3d6248"><path d="M0 0l-10 20h6l-10 15h28L4 20h6Z"/><path d="M0 30v12"/></g></defs><rect width="1000" height="555" fill="#264d59"/><rect width="1000" height="555" fill="url(#water-${school})"/>
 <path d="M60 69Q260-12 404 44L507 57Q783-26 935 80L979 180 958 262 991 351 948 489 763 541 591 510 438 546 248 546 94 501 23 391 31 234 12 139Z" fill="url(#land-${school})" stroke="#d0c69b" stroke-width="4"/>
 <g fill="none" stroke="#e0d5aa" opacity=".3"><path d="M70 100Q230 20 370 90T700 90T930 130M65 116Q240 35 370 106T700 106T930 146M75 132Q240 51 370 122T700 122T930 162M60 435Q190 345 310 451T610 443T930 455M75 450Q190 360 310 466T610 458T920 470"/></g>
 <path d="M559 63Q489 120 549 192T534 306Q493 362 559 416L587 509" fill="none" stroke="#abc4b1" stroke-width="19"/><path d="M559 63Q489 120 549 192T534 306Q493 362 559 416L587 509" fill="none" stroke="#477b88" stroke-width="12"/>
 <path d="M660 333Q701 288 762 319T805 404Q750 457 686 419T660 333Z" fill="#3b6c7d" stroke="#bac6a2" stroke-width="3"/>
 <g aria-hidden="true">${forest}<g fill="#a8aa89" stroke="#526851"><path d="M358 105l39-66 38 66-25-12-13 7-14-11Z"/><path d="M390 117l42-77 46 77-29-13-17 9-18-16Z"/><path d="M890 452l29-51 31 51-22-12-9 7-13-9Z"/></g><g fill="#d2c5a0" stroke="#465948" stroke-width="2"><path d="M210 194v-58l13-25 13 25v34h19v-59l16-32 16 32v59h19v-35l13-25 13 25v59Z"/><path d="M626 431v-28l16-15 16 15v28m9 0v-36l21-20 21 20v36"/></g></g>
 <g class="territories">${areas.map(a=>{const active=school?openLevel(a.id):a.id==='hogwarts',name=school?t(levels[a.id].name):t(regions.find(r=>r.id===a.id).name);return `<path class="territory ${active?'territory-open':'territory-future'} ${String(mapSelection)===String(a.id)?'territory-selected':''}" d="${a.d}" tabindex="0" role="button" data-territory="${a.id}" data-school="${school}" aria-label="${name} · ${t(pair('View region','查看区域'))}"/>`}).join('')}</g>
 <g class="terrain-labels" pointer-events="none">${areas.map(a=>{const name=school?t(levels[a.id].name):t(regions.find(r=>r.id===a.id).name);return `<g transform="translate(${a.x} ${a.y})"><rect x="-105" y="-25" width="210" height="66" rx="8" fill="#18312be8"/><text text-anchor="middle" y="0" fill="#f4e2b3" font-size="20" font-weight="600">${school?String(a.id+1).padStart(2,'0')+' · ':''}${name}</text><text text-anchor="middle" y="25" fill="#c6d9c6" font-size="13">${school?t(cleared.has(levels[a.id].id)?pair('Completed','已完成'):openLevel(a.id)?pair('Current journey','本周旅程'):pair('Locked · view details','待解锁 · 可查看')):t(a.id==='hogwarts'?pair('Enter Hogwarts','进入霍格沃茨'):pair('Coming soon','即将开启'))}</text></g>`}).join('')}</g><g transform="translate(944 35)" fill="#e9d8a4"><path d="M0-20L-7 5 0 0 7 5Z"/><text y="23" text-anchor="middle" font-size="13">N</text></g></svg></div><p class="notice">${t(pair('Tap a territory to discover its story.','点击一片领地，发现它的故事。'))}</p><div id="map-detail" class="map-detail" role="status">${t(pair('Choose a region on the map.','点击地图上的一片区域。'))}</div>`;
}
function bindTerrain(){document.querySelectorAll('[data-territory]').forEach(el=>{const select=()=>{mapSelection=el.dataset.territory;document.querySelectorAll('.territory').forEach(p=>p.classList.toggle('territory-selected',p===el));const school=el.dataset.school==='true';if(school){const i=Number(mapSelection),l=levels[i];$('map-detail').innerHTML=`<h3>${t(l.name)}</h3><p>${t(l.place)}</p><p>${t(l.mission)}</p>${openLevel(i)?`<button id="enter-selected" class="primary">${t(pair('Open this journey','进入本关旅程'))}</button>`:`<p>${t(pair('Not unlocked yet. Complete the weekly puzzle for the previous trial and wait for the next week.','尚未解锁。完成前一关的每周拼图，并等到下一周开放。'))}</p>`}`;if($('enter-selected'))$('enter-selected').onclick=()=>{levelIndex=i;phase='setup';renderHouses();renderPlay()};}else{const r=regions.find(r=>r.id===mapSelection);$('map-detail').innerHTML=`<h3>${t(r.name)}</h3><p>${t(r.sub)}</p>${r.open?`<button id="enter-hogwarts" class="primary">${t(pair('Enter Hogwarts →','进入霍格沃茨小地图 →'))}</button>`:`<p>${t(pair('Your journey here is still to come.','这里的故事，将在未来为你开启。'))}</p>`}`;if($('enter-hogwarts'))$('enter-hogwarts').onclick=()=>goMap('school')}};el.onclick=select;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select()}}})}
function crumbs(){return `<div class="breadcrumbs"><button data-map="world">${t(pair('Wizarding World','魔法世界'))}</button>${phase!=='world'?`<span>›</span><button data-map="school">${t(pair('Hogwarts','霍格沃茨'))}</button>`:''}${!['world','school'].includes(phase)?`<span>›</span><span>01.${levelIndex+1} · ${t(L().name)}</span>`:''}</div>`}
function goMap(destination){if(!['world','school','setup','result'].includes(phase))return;phase=destination;feedback=null;renderHouses();renderPlay()}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
const RULE_VERSION='timed-50-v1',PENALTY_MS=5000;
let recordsDb=null,history=[],recordsReady=false,recordsError='',timerHandle=null,submitting=false,reportWeek=null;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const operationName=op=>t(({add:pair('Addition','加法'),subtract:pair('Subtraction','减法'),mixed:pair('Addition & subtraction','加减混合'),multiply:pair('Times tables 1–9','九九乘法'),all:pair('Add, subtract & multiply','加减乘综合')})[op]);
function budgetMs(c=cfg){return (c.operations==='all'||(c.operations!=='multiply'&&c.range===100)?480:360)*1000}
function duration(ms){const secs=Math.max(0,Math.ceil(ms/1000));return `${Math.floor(secs/60)}:${String(secs%60).padStart(2,'0')}`}
function remainingMs(at=Date.now()){if(!run?.startedAt)return budgetMs();return run.budgetMs-Math.max(0,at-run.startedAt)-run.penaltyMs}
function openRecords(){return new Promise((resolve,reject)=>{const req=indexedDB.open('m-math-hogwarts-learning',1);req.onupgradeneeded=()=>{const db=req.result;db.createObjectStore('runs',{keyPath:'id'});db.createObjectStore('active',{keyPath:'key'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function dbRead(store,key){return new Promise((resolve,reject)=>{const tx=recordsDb.transaction(store,'readonly'),req=key===undefined?tx.objectStore(store).getAll():tx.objectStore(store).get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function dbSave(snapshot,final=false){return new Promise((resolve,reject)=>{if(resettingLocalData){reject(Error("Reset in progress"));return}if(!recordsDb){reject(Error('Records unavailable'));return}const tx=recordsDb.transaction(['runs','active'],'readwrite');tx.objectStore('runs').put(snapshot);if(final)tx.objectStore('active').delete('current');else tx.objectStore('active').put({key:'current',run:snapshot});tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error);tx.onerror=()=>reject(tx.error)})}
function snapshotRun(){const copy=JSON.parse(JSON.stringify(run));copy.houseId=run.houseId||house;copy.metrics=metricsOf(copy);return copy}
function metricsOf(r){let correct=0,attempted=0,wrongQuestions=0,errorAttempts=0;for(let i=0;i<r.questions.length;i++){const a=r.attempts[i]||[];if(a.length){attempted++;if(a[0]===r.questions[i].answer)correct++;const wrong=a.filter(v=>v!==r.questions[i].answer).length;if(wrong)wrongQuestions++;errorAttempts+=wrong}}const end=r.endedAt||Date.now();return{correct,attempted,wrongQuestions,errorAttempts,completed:r.answers.length,elapsedMs:Math.max(0,end-r.startedAt),penaltyMs:r.penaltyMs||0,remainingMs:Math.max(0,r.budgetMs-(end-r.startedAt)-(r.penaltyMs||0))}}
async function persistActive(){try{await dbSave(snapshotRun());recordsError='';return true}catch{recordsError=t(pair('Saving failed. Keep this page open and export your records.','保存失败，请保留此页面并导出记录。'));return false}}
async function refreshHistory(){if(recordsDb){try{history=await dbRead('runs')}catch{recordsError=t(pair('Could not read learning records.','无法读取学习记录。'))}}renderReports()}
function generate(){const plus=[],minus=[],times=[];for(let a=0;a<=cfg.range;a++)for(let b=0;b<=cfg.range;b++){if(a+b<=cfg.range)plus.push({a,b,op:'+',answer:a+b});if(a>=b)minus.push({a,b,op:'−',answer:a-b})}for(let b=1;b<=9;b++)for(let a=1;a<=b;a++)times.push({a,b,op:'×',answer:a*b});shuffle(plus);shuffle(minus);shuffle(times);let qs;if(cfg.operations==='multiply'){qs=[...times,...shuffle([...times]).slice(0,5).map(q=>({...q}))];for(let n=0;n<30;n++){shuffle(qs);if(qs.every((q,i)=>i===0||q.a!==qs[i-1].a||q.b!==qs[i-1].b))break}}else if(cfg.operations==='all')qs=shuffle([...plus.slice(0,17),...minus.slice(0,17),...times.slice(0,16)]);else if(cfg.operations==='add')qs=plus.slice(0,50);else if(cfg.operations==='subtract')qs=minus.slice(0,50);else qs=shuffle([...plus.slice(0,25),...minus.slice(0,25)]);return qs}
function start(){syncWeekly();if(!recordsReady||!recordsDb||!openLevel(levelIndex))return;cfg.count=50;cfg.visible=5;const questions=generate();run={id:crypto.randomUUID(),ruleVersion:RULE_VERSION,week:weekly.week,levelId:L().id,houseId:house,config:{...cfg},timeZone:weekly.timeZone,questions,answers:[],attempts:questions.map(()=>[]),events:questions.map(()=>[]),questionStartedAt:null,startedAt:null,endedAt:null,penaltyMs:0,budgetMs:budgetMs(),index:0,status:'lesson',reward:null};phase='lesson';feedback=null;renderHouses();renderPlay()}
async function beginClock(){if(phase!=='encounter')return;const prior=await dbRead('active','current');if(prior?.run?.id&&prior.run.id!==run.id){recordsError=t(pair('Another unfinished round exists. Reload to continue it.','已有未结束的题组，请刷新后继续。'));renderPlay();return}syncWeekly();run.week=weekly.week;run.startedAt=Date.now();run.questionStartedAt=run.startedAt;run.status='running';run.startDay=dateKey(new Date(run.startedAt),run.timeZone);run.startWeek=weekKey(run.startDay);phase='starting';const saved=await persistActive();if(!saved){phase='encounter';run.startedAt=null;renderPlay();return}screenView='adventure';phase='question';renderPlay();armTimer();$('answer')?.focus({preventScroll:true})}
function armTimer(){clearInterval(timerHandle);timerHandle=setInterval(tickTimer,200);tickTimer()}
function tickTimer(){if(phase!=='question')return;const left=remainingMs();if($('countdown')){$('countdown').textContent=duration(left);$('timer-panel').classList.toggle('urgent',left<=60000)}if(left<=0)finishRound('timeout',Date.now())}
function score(){const m=metricsOf(run);return{...m,retries:run.attempts.reduce((s,a)=>s+Math.max(0,a.length-1),0),pass:run.status==='passed'&&run.answers.length===50&&remainingMs(run.endedAt)>0}}
function feedbackText(){if(!feedback)return '';if(feedback.correct)return `✧ ${S().words}! ${t(pair('Previous question','上一题'))}: ${feedback.a} ${feedback.op} ${feedback.b} = ${feedback.answer}.`;return `${t(pair('Not quite: −5 seconds. Try this question again.','答错扣除 5 秒，请继续计算当前题。'))} ${t(H().cue)}`}
async function submit(e){e.preventDefault();if(phase!=='question'||submitting)return;const at=Date.now();if(remainingMs(at)<=0){await finishRound('timeout',at);return}const raw=$('answer').value.trim();if(!/^\d+$/.test(raw)||!Number.isSafeInteger(Number(raw))){$('answer-feedback').textContent=t(pair('Enter a whole number, including 0. The timer continues.','请输入非负整数，0 也可以；倒计时继续。'));return}submitting=true;try{const q=run.questions[run.index],value=Number(raw),correct=value===q.answer;run.attempts[run.index].push(value);run.events[run.index].push({value,correct,at,questionElapsedMs:Math.max(0,at-run.questionStartedAt),runElapsedMs:Math.max(0,at-run.startedAt),penaltyMs:correct?0:PENALTY_MS});feedback={...q,correct};if(!correct){run.penaltyMs+=PENALTY_MS;if(remainingMs(at)<=0){await finishRound('timeout',at);return}await persistActive();if(phase!=='question')return;renderPlay();$('answer').value=raw;$('answer').focus({preventScroll:true});$('answer').select();return}run.answers.push({value,correct:run.attempts[run.index][0]===q.answer});if(run.answers.length===50){await finishRound('passed',at);return}run.index++;run.questionStartedAt=at;await persistActive();if(phase!=='question')return;renderPlay();$('answer').focus({preventScroll:true})}finally{submitting=false}}
async function finishRound(status,at=Date.now()){if(!run?.startedAt||['settling','result'].includes(phase))return;phase='settling';clearInterval(timerHandle);run.status=status;run.endedAt=at;run.finishedWeek=weekKey(dateKey(new Date(at),run.timeZone));if($('answer'))$('answer').disabled=true;let saved=await persistActive();if(status==='passed'&&saved){await awardRound()}else run.reward={reason:status==='passed'?'storage':status};if(run.reward?.earned)run.reward.week=weekly.week;try{await dbSave(snapshotRun(),true)}catch{recordsError=t(pair('Result save failed. Export records before closing this page.','结算保存失败，关闭前请导出记录。'))}const snap=snapshotRun();history=history.filter(r=>r.id!==snap.id);history.push(snap);phase='result';renderHouses();renderPlay();renderReports()}
async function restoreRecords(){try{recordsDb=await openRecords();history=await dbRead('runs');const active=await dbRead('active','current');recordsReady=true;if(active?.run){const r=active.run;if(r.ruleVersion===RULE_VERSION&&r.questions?.length===50&&Array.isArray(r.events)&&r.config){run=r;Object.assign(cfg,r.config,{count:50,visible:5});levelIndex=levels.findIndex(l=>l.id===r.levelId);house=r.houseId||house;player.house=house;savePlayer();if(levelIndex<0)throw Error('Unknown level');phase='question';if(r.status==='passed'||r.status==='timeout'||r.status==='abandoned'){const status=r.status;run.rewardHandled=false;await finishRound(status,r.endedAt)}else if(remainingMs()<=0){await finishRound('timeout')}else{renderAll();armTimer()}}else{recordsError=t(pair('An incompatible unfinished round was preserved; export your records before continuing.','发现不兼容的未完成题组，已保留，请先导出记录。'));recordsReady=false}}renderAll()}catch{recordsReady=true;recordsError=t(pair('Learning-record storage is unavailable. Allow browser storage and reload. Timed rounds cannot start until records can be saved.','学习记录存储不可用，请允许浏览器存储后刷新；能保存记录后才可开始限时练习。'));renderAll()}}
function statusName(s){return t(({running:pair('In progress','进行中'),passed:pair('Passed','通过'),timeout:pair('Timed out','超时'),abandoned:pair('Ended early','主动结束')})[s]||pair('Unknown','未知'))}
function timerMarkup(){return `<div class="timer-panel" id="timer-panel"><div><small>${t(pair('50 QUESTIONS · TIME LEFT','50 道题 · 剩余时间'))}</small><strong id="countdown">${duration(remainingMs())}</strong></div><div><span>${t(pair('Every wrong attempt: −5 s','每次答错：扣 5 秒'))}</span><br><small>${t(pair('Penalty so far','已扣时间'))}: ${run.penaltyMs/1000}s · ${t(pair('Budget','本轮时限'))}: ${duration(run.budgetMs)}</small></div></div>`}
function multiplicationTable(){return `<details class="times-table"><summary>${t(pair('Review the 1–9 multiplication table before starting','开始前复习九九乘法表'))}</summary><div class="table-wrap"><table><tbody>${Array.from({length:9},(_,b)=>`<tr>${Array.from({length:b+1},(_,a)=>`<td>${a+1} × ${b+1} = ${(a+1)*(b+1)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details>`}
