const PLAYER_KEY='m-math-hogwarts-player-v1';
let player={name:'',house:null,lang:'zh'},exploreStep=0,screenView='adventure';
try{const saved=JSON.parse(localStorage.getItem(PLAYER_KEY)||'null');if(saved&&houses.some(h=>h.id===saved.house))player={name:String(saved.name||'').slice(0,20),house:saved.house,lang:saved.lang==='en'?'en':'zh'}}catch{}
lang=player.lang;house=player.house||'gryffindor';phase='welcome';
function savePlayer(){if(resettingLocalData)return;player.house=house;player.lang=lang;try{localStorage.setItem(PLAYER_KEY,JSON.stringify(player))}catch{}}
function heading(n,en,zh){return `<p class="eyebrow">${t(pair('HOGWARTS · YOUR ADVENTURE','霍格沃茨 · 你的冒险'))}</p><h2>${t(pair(en,zh))}</h2>`}
function updateConfig(){}
function renderHouses(){}
function renderStatic(){document.documentElement.lang=lang==='zh'?'zh-CN':'en';renderChrome()}
function activeRound(){return ['question','starting','settling'].includes(phase)}
function renderChrome(){const active=activeRound();$('game-header').innerHTML=`<a class="wordmark" href="#" id="brand-home"><span class="brand-star">✦</span><span>M MATH<small>HOGWARTS</small></span></a><nav aria-label="${t(pair('Game navigation','游戏导航'))}">${[['adventure','Adventure','冒险'],['puzzle','Puzzle album','拼图册'],['creatures','Field guide','生物图鉴'],['parents','Parent journal','家长中心']].map(([id,en,zh])=>`<button data-view="${id}" class="nav-button ${screenView===id?'selected':''}" ${active?'disabled':''}>${t(pair(en,zh))}</button>`).join('')}</nav><div class="header-tools">${player.house?`<img class="mini-crest" src="${ASSETS[house]}" alt="${t(H().name)}"><span class="player-name">${esc(player.name||t(pair('Young witch','小巫师')))}</span>`:''}<button id="music-toggle" class="music-toggle" aria-pressed="false">♫ 音乐</button><button id="language" class="language-button">${lang==='zh'?'EN':'中文'}</button></div>`;
window.syncGameMusic?.();
$('language').onclick=()=>{const draft=$('answer')?.value;lang=lang==='zh'?'en':'zh';savePlayer();renderAll();if($('answer')&&draft!==undefined){$('answer').value=draft;$('answer').focus({preventScroll:true})}};
$('brand-home').onclick=e=>{e.preventDefault();if(active)return;screenView='adventure';phase='welcome';renderPlay()};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
}
function showView(view){if(activeRound())return;screenView=view;if(view==='adventure'&&!['welcome','sorting','world','school','setup','result'].includes(phase))phase='world';renderPlay();window.scrollTo({top:0,behavior:'instant'})}
function gameButton(id,en,zh,secondary=false){return `<button id="${id}" class="${secondary?'secondary':'primary'}">${t(pair(en,zh))}</button>`}
function regionNav(){return `<div class="breadcrumbs"><button data-route="world">${t(pair('Wizarding World','魔法世界'))}</button>${phase!=='world'?`<span>›</span><button data-route="school">${t(pair('Hogwarts','霍格沃茨'))}</button>`:''}${!['world','school'].includes(phase)?`<span>›</span><span>${t(L().name)}</span>`:''}</div>`}
function puzzleMarkup(level=weekly.level){const collected=cleared.has(levels[level].id)?12:level===weekly.level?weekly.pieces:0;return `<div class="puzzle-grid" role="img" aria-label="${t(levels[level].name)} ${collected}/12">${Array.from({length:12},(_,i)=>`<div class="puzzle-piece ${i<collected?'collected':'missing'}" style="${i<collected?`background-image:url('${ASSETS[levels[level].id]}');background-position:${(i%4)*100/3}% ${Math.floor(i/4)*50}%`:''}"><span>${i<collected?'':i+1}</span></div>`).join('')}</div>`}
function compactWeek(){return `<div class="week-summary"><div><span class="eyebrow">${t(pair('THIS WEEK’S JOURNEY','本周旅程'))}</span><strong>${t(levels[weekly.level].name)}</strong></div><div class="week-fragments"><b>${weekly.pieces}</b><span>/ 12 ${t(pair('pieces','碎片'))}</span></div><div class="mini-meter"><span style="width:${weekly.pieces/12*100}%"></span></div><small>${t(pair('Today','今日'))} ${weekly.days[dateKey()]||0}/3</small></div>`}
function weekExplanation(){return weekly.pieces===12?reasonText(weekly.completed.length===6?'chapter':'week'):t(pair('One successful round, one piece. Collect 12 this week to complete the portrait.','一轮成功，一片拼图。本周集齐 12 片，揭开完整的神奇生物画像。'))}
function renderPlay(){syncWeekly();renderChrome();$('records').hidden=screenView!=='parents';$('game-screen').hidden=screenView==='parents';$('records').className='parent-screen';if(screenView==='parents'){renderReports();return}const l=L(),s=S();let content='';$('game-screen').dataset.phase=phase;
if(screenView==='puzzle'){content=`<div class="page-intro"><p class="eyebrow">THE COLLECTOR’S ALBUM</p><h1>${t(pair('A little magic, every day.','每天一点，拼出魔法。'))}</h1><p>${weekExplanation()}</p></div><div class="album-layout"><article class="panel">${weeklyPanel()}</article><aside class="album-seals"><h3>${t(pair('Chapter one','第一章'))}</h3>${levels.map((v,i)=>`<div class="seal ${cleared.has(v.id)?'earned':''}"><span>${cleared.has(v.id)?'✦':String(i+1).padStart(2,'0')}</span><div><strong>${t(v.name)}</strong><small>${t(cleared.has(v.id)?pair('Portrait complete','画像已完成'):i===weekly.level?pair('In progress','正在收集'):pair('A future adventure','未来的冒险'))}</small></div></div>`).join('')}</aside></div>`;
}else if(screenView==='creatures'){content=`<div class="page-intro"><p class="eyebrow">HAGRID’S FIELD GUIDE</p><h1>${t(pair('Meet the magical world.','认识神奇的它们。'))}</h1><p>${t(pair('Observe with care. Learn the right spell. Every creature has a story.','用心观察，学会恰当的魔法。每一种生物都有自己的故事。'))}</p></div><div class="creature-library">${levels.map(v=>`<article class="creature-card">${art(v.id)}<div><span class="eyebrow">${v.name.en}</span><h2>${t(v.name)}</h2><p>${t(v.desc)}</p><div class="spell-label">✦ ${spells[v.spell].words}</div></div></article>`).join('')}</div>`;
}else if(phase==='welcome'){
content=`<div class="welcome-scene"><div class="welcome-shade"></div><div class="welcome-copy"><p class="eyebrow">A LETTER FROM HOGWARTS</p><h1>${t(pair('Your magic<br>starts here.','你的魔法，<br>从这里开始。'))}</h1><p>${t(pair('A letter. A wand. A world waiting for you.<br>Learn your spells, meet magical creatures, and take your first steps toward becoming an Auror.','一封录取信，一支魔杖，一个等你探索的世界。<br>学习魔法，认识神奇生物，踏上成为傲罗的旅程。'))}</p><button id="enter-game" class="primary grand" ${!recordsReady||!recordsDb?'disabled':''}>${!recordsReady?t(pair('Opening your letter…','正在打开录取信…')):t(player.house?pair('Continue my adventure →','继续我的冒险 →'):pair('Open my Hogwarts letter →','打开霍格沃茨来信 →'))}</button><div class="welcome-facts"><span>✦ ${t(pair('50 sums. One spellbound journey.','50 道计算，一段魔法旅程。'))}</span><span>◈ ${t(pair('Collect a new piece each round.','每轮练习，收集一片拼图。'))}</span></div></div><div class="scene-caption">THESTRAL<br><span>FORBIDDEN FOREST</span></div></div>`;
}else if(phase==='sorting'){
content=`<div class="page-intro centered"><p class="eyebrow">THE SORTING CEREMONY</p><h1>${t(pair('Where will you belong?','你的故事，属于哪个学院？'))}</h1><p>${t(pair('Four houses. Four ways to shine. Choose the qualities you want to grow.','四个学院，四种闪光的品质。选择你想成为的自己。'))}</p><label class="name-field">${t(pair('Your wizard name','你的小巫师名字'))}<input id="player-name" maxlength="20" value="${esc(player.name)}" placeholder="${t(pair('Young witch','小巫师'))}"></label></div><div class="sorting-houses">${houses.map(h=>`<button data-house="${h.id}" class="sorting-house ${house===h.id?'chosen':''}" style="--house:${h.color}" aria-pressed="${house===h.id}"><img src="${ASSETS[h.id]}" alt="${t(h.name)}"><h2>${t(h.name)}</h2><span>${h.name.en}</span><p>${t(h.traits)}</p></button>`).join('')}</div><div class="sorting-choice"><p>${t(H().story)}</p>${gameButton('confirm-house','This is my house →','这就是我的学院 →')}</div>`;
}else if(phase==='world'){
content=`<div class="page-intro map-intro"><div><p class="eyebrow">THE WIZARDING WORLD</p><h1>${t(pair('An extraordinary world awaits.','魔法世界，等待你的脚步。'))}</h1></div><span class="chapter-tag">${t(pair('Chapter 01 · Hogwarts','第一章 · 霍格沃茨'))}</span></div><div class="map-layout"><div class="map-main">${terrainMap(false)}</div><div class="journey-side">${compactWeek()}${puzzleMarkup()}<p>${weekExplanation()}</p>${gameButton('quick-school','Travel to Hogwarts →','前往霍格沃茨 →')}</div></div>`;
}else if(phase==='school'){
content=`${regionNav()}<div class="page-intro map-intro"><div><p class="eyebrow">HOGWARTS · CHAPTER ONE</p><h1>${t(pair('Your first magical footsteps.','你的第一段魔法旅程。'))}</h1></div><span class="chapter-tag">${cleared.size} / 6 ${t(pair('portraits','幅画像'))}</span></div><div class="map-layout"><div class="map-main">${terrainMap(true)}</div><div class="journey-side">${compactWeek()}${art(levels[weekly.level].id)}<p>${t(levels[weekly.level].mission)}</p><button class="primary" id="current-level">${t(pair('Enter this week’s journey →','进入本周旅程 →'))}</button><small>${t(pair('New territory opens after completing 12 pieces and waiting for the next week.','集齐 12 片后，下一片领地将在下周开放。'))}</small></div></div>`;
}else if(phase==='setup'){
content=`${regionNav()}<div class="mission-layout"><div class="mission-portrait">${art(l.id)}<div><span class="eyebrow">CHAPTER 01 · ${String(levelIndex+1).padStart(2,'0')}</span><h1>${t(l.name)}</h1><p>${t(l.place)}</p></div></div><div class="mission-settings"><p class="eyebrow">PREPARE YOUR WAND</p><h2>${t(pair('Choose today’s practice.','今天，练习哪一种魔法？'))}</h2><p>${t(l.mission)}</p><div class="practice-options">${[['mixed','＋ −','Addition & subtraction','加减混合'],['add','＋','Addition','加法'],['subtract','−','Subtraction','减法'],['multiply','×','Times tables','九九乘法'],['all','＋ − ×','All three','加减乘综合']].map(([id,icon,en,zh])=>`<button data-operation="${id}" class="practice-option ${cfg.operations===id?'chosen':''}" aria-pressed="${cfg.operations===id}"><b>${icon}</b><span>${t(pair(en,zh))}</span></button>`).join('')}</div>${cfg.operations!=='multiply'?`<div class="range-buttons"><span>${t(pair('Number range','数字范围'))}</span>${[20,100].map(n=>`<button data-range="${n}" class="${cfg.range===n?'chosen':''}">0–${n}</button>`).join('')}</div>`:''}<div class="rules-strip"><span><b>50</b>${t(pair('questions','道题'))}</span><span><b>${duration(budgetMs())}</b>${t(pair('countdown','倒计时'))}</span><span><b>−5s</b>${t(pair('per mistake','每次答错'))}</span></div><button id="begin" class="primary wide" ${!recordsReady||!recordsDb?'disabled':''}>${t(pair('Learn my spell →','学习本关魔法 →'))}</button>${rewardReason()?`<p class="notice">${reasonText(rewardReason())}</p>`:`<p class="reward-caption">◈ ${t(pair('Complete this round to earn one puzzle piece.','完成这一轮，获得一片拼图。'))}</p>`}${multiplicationTable()}</div></div>`;
}else if(phase==='lesson'||phase==='practised'){
content=`<div class="lesson-screen"><button id="lesson-back" class="text-button">← ${t(pair('Back to preparation','返回准备'))}</button><div class="spell-orbit" aria-hidden="true">✦</div><p class="eyebrow">YOUR SPELLBOOK · ${t(l.name)}</p><h1>${s.words}</h1><h2>${t(s.name)}</h2><p>${t(s.effect)}</p><p class="gesture">${t(s.gesture)}</p>${phase==='practised'?`<div class="spell-confirmation" role="status">✧ ${t(pair('Your wand glows. You’re ready.','魔杖亮起来了，你准备好了。'))}</div>${gameButton('meet','Set out on my adventure →','出发，进入冒险 →')}`:gameButton('practise','Practise the spell','试着挥动魔杖')}<small>${t(pair('The countdown starts after you meet the creature.','遇见生物并准备好后，才开始倒计时。'))}</small></div>`;
}else if(phase==='explore'){
content=`<div class="explore-scene" style="--scene:url('${ASSETS[l.id]}');--zoom:${1+exploreStep*.06}"><div class="explore-vignette"></div><div class="explore-top"><span>${t(l.place)}</span><span>${exploreStep} / 3</span></div><div class="explore-copy"><p class="eyebrow">FOLLOW THE PATH</p><h1>${t([pair('The path is waiting.','小径正在前方。'),pair('A rustle among the trees.','树影间传来细细的声响。'),pair('Something magical is close.','神奇的身影，越来越近。')][Math.min(exploreStep,2)])}</h1><p>${t(H().cue)}</p>${gameButton('walk','Step forward ↑','向前走一步 ↑')}<small>${t(pair('Press ↑ or W to walk. No timer yet.','按 ↑ 或 W 也能前进；探索阶段不计时。'))}</small></div></div>`;
}else if(phase==='encounter'){
content=`<div class="encounter-screen"><div class="encounter-art">${art(l.id)}<span class="entrance-caption">${t(l.action)}</span></div><div class="encounter-info"><p class="eyebrow">${l.name.en}</p><h1>${t(l.name)}</h1><p>${t(l.desc)}</p><div class="equipped-spell"><span>✦</span><div><small>${t(pair('Equipped spell','已学会魔法'))}</small><strong>${s.words}</strong></div></div><p>${t(pair('50 questions. Keep your wand steady. Correct answers carry your magic forward.','50 道题，稳稳握住魔杖。每次准确计算，都让魔法向前一步。'))}</p><button id="ready" class="primary wide">${t(pair('I’m ready — start','准备好了，开始施法'))} · ${duration(budgetMs())}</button><small>${t(pair('A wrong answer stays in place and costs 5 seconds.','答错留在原题重试，并扣除 5 秒。'))}</small></div></div>`;
}else if(phase==='starting'||phase==='settling'){
content=`<div class="loading-screen"><span>✦</span><h2>${t(pair('Your magic is taking shape…','魔法正在汇聚……'))}</h2></div>`;
}else if(phase==='question'){
const stats=score(),attempts=run.attempts[run.index];content=`<div class="battle-screen"><div class="battle-arena ${feedback?.correct?'cast-success':''}" style="--scene:url('${ASSETS[l.id]}')"><div class="arena-shade"></div><div class="battle-top"><div><p class="eyebrow">${t(l.place)}</p><h1>${t(l.name)}</h1><span>${t(H().name)} · ${s.words}</span></div>${timerMarkup()}</div><div class="magic-trail" aria-hidden="true">✧</div><div class="arena-bottom"><span>${t(l.goal)}</span><span>${run.answers.length} / 50</span><div class="meter"><span style="width:${run.answers.length*2}%"></span></div></div></div><div class="answer-desk"><div class="queue" style="grid-template-columns:repeat(5,minmax(0,1fr))">${run.questions.slice(run.index,run.index+5).map((q,i)=>`<div class="q ${i===0?'current':''} ${i===0&&attempts.length?'needs-retry':''}"><small>${i===0?t(attempts.length?pair('TRY AGAIN','再试一次'):pair('CAST NOW','当前题')):t(pair('UP NEXT','下一道'))} · ${run.index+i+1}</small><strong>${q.a} ${q.op} ${q.b}</strong><small>= ?</small></div>`).join('')}</div><form id="answer-form" class="answer-row"><label for="answer">${t(pair('Your answer','你的答案'))}</label><input id="answer" inputmode="numeric" autocomplete="off" aria-describedby="answer-feedback" aria-label="${t(pair('Answer to current question','当前题的答案'))}"><button class="primary" type="submit">${t(pair('Cast spell ↵','施法 ↵'))}</button></form><div class="feedback-live" id="answer-feedback" role="status">${feedbackText()||t(pair('Enter your answer and press Enter.','输入答案，按回车施展魔法。'))}</div><div class="battle-foot"><span>${t(pair('First try','首次答对'))} ${stats.correct}/${stats.attempted}</span><button id="leave" class="text-button">${t(pair('End this round','结束本轮'))}</button></div></div></div>`;
}else if(phase==='result'){
const stats=score();content=`<div class="result-screen"><div class="result-emblem">${run.reward?.earned?'◈':run.status==='passed'?'✦':'↻'}</div><p class="eyebrow">${statusName(run.status)}</p><h1>${t(run.status==='timeout'?pair('The magic needs another try.','再试一次，魔法就在前方。'):run.status==='abandoned'?pair('Your journey is saved.','这段旅程，已为你记下。'):run.reward?.earned?pair('A new piece of magic.','又拼出了一片魔法。'):pair('Beautifully cast!','魔法施展成功！'))}</h1><p>${run.reward?.earned?t(pair('50 questions complete. One new piece for your weekly portrait.','50 题完成，本周的画像又多了一片。')):run.status==='passed'?reasonText(run.reward?.reason):t(pair('Your answers have been saved. A fresh set of questions is ready when you are.','作答和错题已经记录。准备好了，就用一组新题重新挑战。'))}</p><div class="result-layout"><div class="result-puzzle">${puzzleMarkup(levelIndex)}<strong>${levelIndex===weekly.level?weekly.pieces:12} / 12</strong></div><div class="result-stats"><div><strong>${stats.completed}/50</strong><span>${t(pair('questions completed','完成题数'))}</span></div><div><strong>${duration(stats.elapsedMs)}</strong><span>${t(pair('time used','实际用时'))}</span></div><div><strong>${stats.wrongQuestions}</strong><span>${t(pair('questions to revisit','需要复习的题'))}</span></div><div><strong>${run.penaltyMs/1000}s</strong><span>${t(pair('time penalty','累计扣时'))}</span></div></div></div><div class="result-actions">${gameButton('chapter-map','Return to my map','回到我的地图')}${gameButton('retry','Practise another round','再练习一轮',true)}</div><button id="result-report" class="text-button">${t(pair('View learning journal →','查看本轮记录与错题 →'))}</button></div>`;
}
$('game-screen').innerHTML=content+(recordsError?`<div class="save-error" role="alert">${esc(recordsError)}</div>`:'')+(storageError?`<div class="save-error">${t(pair('Weekly progress cannot be saved. Check browser storage.','周进度无法保存，请检查浏览器存储设置。'))}</div>`:'');
bindGame();
}
function bindGame(){bindTerrain();
const on=(id,fn)=>{if($(id))$(id).onclick=fn};
on('enter-game',()=>{phase=player.house?'world':'sorting';renderPlay()});
document.querySelectorAll('[data-house]').forEach(b=>b.onclick=()=>{player.name=$('player-name').value.trim();house=b.dataset.house;renderPlay()});
on('confirm-house',()=>{player.name=$('player-name').value.trim();savePlayer();phase='world';renderPlay()});
on('quick-school',()=>{phase='school';renderPlay()});on('current-level',()=>{levelIndex=weekly.level;phase='setup';renderPlay()});
document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{phase=b.dataset.route;renderPlay()});
document.querySelectorAll('[data-operation]').forEach(b=>b.onclick=()=>{cfg.operations=b.dataset.operation;renderPlay()});document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{cfg.range=Number(b.dataset.range);renderPlay()});
on('begin',start);on('lesson-back',()=>{phase='setup';renderPlay()});on('practise',()=>{phase='practised';renderPlay()});on('meet',()=>{exploreStep=0;phase='explore';renderPlay()});on('walk',walkForward);on('ready',beginClock);
if($('answer-form')){$('answer-form').onsubmit=submit;$('answer').onkeydown=e=>{if(e.key==='Enter'&&e.repeat)e.preventDefault()};}
on('leave',()=>finishRound('abandoned'));on('retry',start);on('chapter-map',()=>{phase='school';renderPlay()});on('result-report',()=>showView('parents'));
}
function walkForward(){if(phase!=='explore')return;exploreStep++;if(exploreStep>=3)phase='encounter';renderPlay()}
document.addEventListener('keydown',e=>{if(phase==='explore'&&screenView==='adventure'&&!e.repeat&&['ArrowUp','w','W'].includes(e.key)){e.preventDefault();walkForward()}});
function renderAll(){renderStatic();renderPlay()}

document.addEventListener('visibilitychange',()=>{if(!document.hidden&&['world','school','setup','result'].includes(phase))renderPlay()});
window.addEventListener('storage',e=>{if(e.key===WEEKLY_KEY&&['world','school','setup','result'].includes(phase))renderPlay()});
renderAll();restoreRecords();
