# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: windse7en's blog
subtitle: while(1){slef++;}
description:
author: Tao Zhang
language:
  - en
  - zh-Hans
timezone: America/Winnipeg

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
  随笔: untag

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: next
# theme: yilia

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/windse7en/windse7en.github.io.git
  branch: master

# # jsonContent
# jsonContent:
#   meta: false
#   pages: false
#   posts:
#     title: true
#     date: true
#     path: true
#     text: true
#     raw: false
#     content: false
#     slug: false
#     updated: false
#     comments: false
#     link: false
#     permalink: false
#     excerpt: false
#     categories: false
#     tags: true

# customized by Tao Zhang
avatar: /images/avatar.jpg

google_analytics: UA-65569497-1

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

sitemap:
  path: sitemap.xml

# Social links
social:
  GitHub: https://github.com/windse7en
  Twitter: https://twitter.com/windse7en52

# Share
jiathis: true
